## Задача 1. Ток вероятности

Выведите уравнения [-@eq-interference-probability-current-one] и
[-@eq-interference-probability-current-two] для комплексного $H_{12}$.
Найдите относительную фазу, при которой поток из состояния 1 в состояние 2
максимален.

## Задача 2. Две полные амплитуды

Пусть $|d|=0.48516$, $|f|=0.48580$ и
$\arg(f/d)=(-1+0.00221)\pi$. Вычислите $|d+f|^2$. Почему нельзя получить
правильный ответ, сложив $|d|^2$ и $|f|^2$?

## Задача 3. Адиабатический пропагатор

Перемножьте три матрицы в уравнении
[-@eq-interference-adiabatic-propagator] для $\alpha_x=0$. Подставьте
начальное состояние [-@eq-interference-initial-upper-mode] и покажите, что
конечное $c_1$ равно нулю при любых динамических фазах $E_1$ и $E_2$.

## Задача 4. Тонкий слой

Для пропагатора [-@eq-interference-resonant-layer] и равных входных модулей
найдите значения $\varepsilon$ и $\gamma$, при которых $P_1$ минимальна.
Куда переходит недостающая вероятность?

## Задача 5. Работа привода

Выведите линейное уравнение для маятника с меняющейся длиной $\ell(t)$,
используя горизонтальное смещение $x=\ell\vartheta$. Покажите происхождение
члена $-\ddot\ell/\ell$. При каких условиях привод не меняет среднюю энергию
за один быстрый период?
