project:
  type: default
  render:
    - index.qmd
    - slides/00_solar_neutrino_physics.qmd
    - slides/00_solar_neutrino_physics_appendix.qmd
    - slides/01_solar_sources.qmd
    - slides/02_msw_detector_statistics.qmd
    - assignments/sk_integrated_project.qmd
    - "!slides/03_student_defense.qmd"
    - "!assignments/defense_requirements.qmd"
    - "!assignments/fit_recipes.qmd"
    - "!notebooks/*.ipynb"

lang: en

format:
  html:
    css:
      - assets/css/custom.css
    toc: false

execute:
  echo: false
  warning: false
  message: false
