project:
  type: default
  render:
    - index.qmd
    - slides/*.qmd
    - assignments/*.qmd
    - notebooks/*.ipynb

lang: en

format:
  html:
    css:
      - assets/css/custom.css
    toc: false

execute:
  echo: false
  warning: false
  message: false
